### ISSUE TITLE
Not Annotating Namespaced Models

### ISSUE THREAD

**Issue by akayvanfar** [ctran/annotate_models#253] opened 2015-06-01 17:49 UTC
For some reason, the gem isn't annotating our namespaced models. Any idea why this could be happening?

**Comment by ctran** [comment] 2015-06-09 19:31
That is not much information for me to even guess.

**Comment by akayvanfar** [comment] 2015-06-09 19:37
Sorry. Here is the example.

Here is the model info: 
`class Foo::Bar < ActiveRecord::Base` with the file nested in one of our engines in `/engines/common/app/models/foo/bar.rb` and the table created as `foo_bars` in our schema.

However, when we run migrations the gem does not annotate this file.

**Comment by ctran** [comment] 2015-06-10 02:14
Ah, I don't think engine is supported yet, #190

**Comment by akayvanfar** [comment] 2015-06-10 17:17
So it actually annotates in all of our non-namespaced models that are all also in our engines. It's just the models namespaced under modules that don't get annotated.

**Comment by ctran** [comment] 2015-06-10 19:49
Ah, maybe I will take a closer look this weekend.

**Comment by akayvanfar** [comment] 2015-06-11 02:27
Thanks @ctran !

**Comment by ttxtosca** [comment] 2015-07-06 20:32
+1, it would be nice to have this feature

**Comment by mainameiz** [comment] 2015-08-09 09:23
@ctran annotating models that uses table_name isn't supprted too?

e.g.

```ruby
class Model < AR
  table_name = 'not_standard_table_name'
end
```

**Comment by hx** [comment] 2015-09-25 10:43
:+1:

**Comment by ctran** [comment] 2015-12-27 09:36
I'm having trouble reproducing this, mostly due to my inexperience with setting up engines.  Is it possible for you to create a sample app that can reproduce this?

**Comment by vfonic** [comment] 2015-12-28 16:29
I just added annotate gem to seoable gem that is a rails engine. I guess it should annotate the Seoable::SeoDetail, but it doesn't annotate anything.

You can find seoable gem here:
https://github.com/DVELP/seoable

**Comment by ctran** [comment] 2015-12-29 04:47
So you are running "annotate" directly from your gem?  Can you give me the command you use?

**Comment by ctran** [comment] 2015-12-29 04:56
I need a sample rails app that can demonstrate this.  Otherwise, I will close this out :-)

**Comment by mainameiz** [comment] 2015-12-29 08:05
I will make a sample app after holidays, I swear.

**Comment by vfonic** [comment] 2015-12-29 10:04
I just added the 'annotate' gem as development dependency in .gemspec file and ran bundle install followed by annotate. I got: "Nothing to annotate"
I don't how is annotate supposed to be working for gems, whether it should annotate these models or not.

**Comment by ctran** [comment] 2015-12-30 00:05
@vfonic annotate needs "schema info" so it won't work in your scenario.

**Comment by z0ny** [comment] 2017-10-15 17:23
In my example i think gem should annotate Y class and Y::B class where Y is parent of B class. If Y is module and B extends AR, then everything is ok, but if Y is class annotate does nothing.

example:

```
class Y < ApplicationRecord
  # Or with
  # self.abstract_class = true
end

class Y
  class B < Y
  end
end
```

example project: https://github.com/z0ny/annotate_namespaces

**Closed** 2019-02-14 16:39 UTC
Labels: feature

**Comment by sposmen** [comment] 2020-01-16 21:43
I had the same issue. To make it work instead of using the `table_name_prefix` in the module I used the `table_name` set like:
```ruby
class Foo::Bar < ActiveRecord::Base
  self.table_name = 'foo_bar'
end
```
And now it worked also in the engine using the `rake app:annotate_models` after the annotate installation.
