### ISSUE TITLE
Does not annotate factories after DB migration

### ISSUE THREAD

**Issue by heaven** [ctran/annotate_models#340] opened 2016-02-02 11:55 UTC
Here's my config:

``` ruby
Annotate.set_defaults(
  'routes'                  => 'false',
  'position_in_routes'      => 'after',
  'position_in_class'       => 'after',
  'position_in_test'        => 'after',
  'position_in_fixture'     => 'after',
  'position_in_factory'     => 'after',
  'position_in_serializer'  => 'after',
  'show_foreign_keys'       => 'true',
  'show_indexes'            => 'true',
  'simple_indexes'          => 'false',
  'model_dir'               => 'app/models',
  'root_dir'                => '',
  'include_version'         => 'false',
  'require'                 => '',
  'exclude_tests'           => 'false',
  'exclude_fixtures'        => 'false',
  'exclude_factories'       => 'false',
  'exclude_serializers'     => 'false',
  'exclude_scaffolds'       => 'false',
  'exclude_controllers'     => 'true',
  'exclude_helpers'         => 'true',
  'ignore_model_sub_dir'    => 'false',
  'ignore_columns'          => nil,
  'ignore_unknown_models'   => 'false',
  'hide_limit_column_types' => 'integer,boolean',
  'skip_on_db_migrate'      => 'false',
  'format_bare'             => 'true',
  'format_rdoc'             => 'false',
  'format_markdown'         => 'false',
  'sort'                    => 'false',
  'force'                   => 'false',
  'trace'                   => 'false',
  'wrapper_open'            => nil,
  'wrapper_close'           => nil,
)
end
```

After running migration it updates annotations in models, but not in factories, then I have to run `bundle exec annotate` to annotate factories:

```
➜  clarion-core git:(master) ✗ rake db:migrate
== 20160202113832 AddMaxDailyCountToReminder: migrating =======================
-- add_column(:reminders, :max_daily_count, :integer, {:default=>1, :null=>false})
   -> 0.0498s
== 20160202113832 AddMaxDailyCountToReminder: migrated (0.0499s) ==============

Annotated (1): app/models/reminder.rb

➜  clarion-core git:(master) ✗ bundle exec annotate
Annotated (1): app/models/reminder.rb

➜  clarion-core git:(master) ✗ bundle exec annotate
Model files unchanged.
```

**Comment by vraravam** [comment] 2016-07-20 03:16
This not only skips annotating factory_girl factories, but also skips rspec files. But, one interesting thing I noticed is that the `annotate` executable DOES annotate all such files while the rake task does not

**Comment by heaven** [comment] 2016-07-20 03:19
Yeah, I now usually do `rake db:migrate && bundle exec annotate` to get things annotated properly.

**Comment by Hirurg103** [comment] 2016-08-25 14:41
is someone working on this?

**Comment by ezekg** [comment] 2016-11-13 06:25
This is happening with serializers as well. I have to run `rails db:migrate && annotate` to get everything annotated correctly.

**Comment by lime** [comment] 2017-03-02 09:33
I managed to trace this to the `root_dir` option. 

With `'root_dir' => ''`, factories are not annotated during migrations. If I comment out the line or change it to `'root_dir' => nil` factory annotations work.

**Comment by lime** [comment] 2017-03-02 09:35
The root cause seems to be that we have a couple of different ways of handling blank values for this option.

[`annotate.rb`](https://github.com/ctran/annotate_models/blob/v2.7.1/lib/annotate.rb#L83):

```ruby
# setup_options
options[:root_dir] = [''] if options[:root_dir].empty?
```

[`annotate_models.rake`](https://github.com/ctran/annotate_models/blob/v2.7.1/lib/tasks/annotate_models.rake#L24):

```ruby
# annotate_models
options[:root_dir] = ENV['root_dir'] ? ENV['root_dir'].split(',') : ['']

# remove_annotation
options[:root_dir] = ENV['root_dir']
```

[`annotate_models.rb`](https://github.com/ctran/annotate_models/blob/v2.7.1/lib/annotate/annotate_models.rb#L81):

```ruby
# root_dir
@root_dir.is_a?(Array) ? @root_dir : [@root_dir || '']
```

Clearly, the intent is for the default value to be `['']`. However, the check inside `annotate_models.rake` ends up turning  `''` into `[]`.

Later, [when looping through `root_dir.each`](https://github.com/ctran/annotate_models/blob/v2.7.1/lib/annotate/annotate_models.rb#L155-L159), the array is empty and a lot of files types are never added.

**Comment by vamsipavanmahesh** [comment] 2017-05-29 04:01
Is this fixed? can you please update this @lime

**Comment by lime** [comment] 2017-05-29 07:39
#448 has been merged, so this should be fixed on the `develop` branch.

However, there hasn't been a new released version in quite some time. Until then, you can [use the unreleased version from github](http://bundler.io/git.html).

**Closed** 2019-02-14 16:40 UTC
Labels: bug
