### ISSUE TITLE
support active model serializers

### ISSUE THREAD

**Issue by simonweil** [ctran/annotate_models#148] opened 2013-11-12 14:19 UTC
Please add support for Active Model Serializers Gem.
https://github.com/rails-api/active_model_serializers

**Comment by rusterholz** [comment] 2015-02-13 23:39
+1! Now that Serializers are included by default in Rails 4, formally adding support for this would be especially desirable. Can this be revisited? Our team would love it.

@drewda's fork appears to have support for this, so AFAIK it should be as simple as pulling in his fork and fixing any borked regressions.

**Comment by drewda** [comment] 2015-02-14 02:20
My PR is features complete, but I didn't add any test coverage. Help from
someone more familiar with the test suite would be great.

**Comment by rusterholz** [comment] 2015-03-27 21:47
@ctran It's been over a year since this issue was opened, and almost five months since @drewda's PR. Could that be merged?

**Comment by ctran** [comment] 2015-03-28 07:15
I don't remember there was a PR on this.

**Comment by drewda** [comment] 2015-04-10 19:38
Two duplicate PRs:

* https://github.com/ctran/annotate_models/pull/213
* https://github.com/ctran/annotate_models/pull/219

In any case, there's now support for serializers.

**Comment by ctran** [comment] 2015-04-10 20:20
Cool!

**Closed by ctran** 2015-04-10 20:20 UTC
Labels: feature

**Comment by simonweil** [comment] 2015-04-12 22:18
Great, thanks!
