### ISSUE TITLE
Issues with ruby 2.6.3 upgrade

### ISSUE THREAD

**Issue by bheemreddy181** [ctran/annotate_models#629] opened 2019-06-18 19:22 UTC
Describe your problem here.

Seeing issues with ruby upgardes

## Commands

```
bundle exec rake cucumber
rake aborted!
Don't know how to build task 'db:migrate:reset' (See the list of available tasks with `rake --tasks`)
Did you mean?  db:migrate:redo
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/annotate-2.7.5/lib/tasks/annotate_models_migrate.rake:8:in `block in <top (required)>'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/annotate-2.7.5/lib/tasks/annotate_models_migrate.rake:7:in `each'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/annotate-2.7.5/lib/tasks/annotate_models_migrate.rake:7:in `<top (required)>'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/annotate-2.7.5/lib/annotate.rb:133:in `block in load_tasks'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/annotate-2.7.5/lib/annotate.rb:132:in `each'
/Users/bvennapureddy/.gem/ruby/2.6.3/gems/annotate-2.7.5/lib/annotate.rb:132:in `load_tasks'

```

## Version

- annotate version : 2.7.5
- rails version : 5.2.3
- ruby version : 2.6.3

**Comment by bheemreddy181** [comment] 2019-06-18 20:14
****** THIS IS A BLOCKER ***************

**Comment by drwl** [comment] 2019-07-07 22:50
Can you provide an isolated example of the code you're using? It's hard to tell what the issue is just from looking at the stacktrace.

**Comment by drwl** [comment] 2019-09-30 21:13
Closing this off since this needs more information. @bheemreddy181 feel free to reopen if it's still an issue and you could provide more info.

**Closed by drwl** 2019-09-30 21:13 UTC
Labels: reviewed
