### ISSUE TITLE
No position_in_scaffold parameter

### ISSUE THREAD

**Issue by djsegal** [ctran/annotate_models#301] opened 2015-12-08 08:27 UTC
No `position_in_scaffold` parameter was added when `exclude_scaffolds` was

**Comment by djsegal** [comment] 2015-12-08 08:32
I believe this is the case for controllers and helpers, too

**Comment by djsegal** [comment] 2015-12-08 09:19
Maybe add a test that checks for:
+ one-to-one pairing for `exclude_blank` and `position_in_blank`
+ some other property that exists everywhere, maybe `MATCHED_TYPES`

**Comment by djsegal** [comment] 2015-12-08 09:57
Piggybacking on this issue:

--------

Pattern names should be refactored for clarity purposes (// i.e. `MATCHED_TYPES`)
+ `test` –> `class_test`
+ `scaffold` –> 
  - `controller_test`
  - `request`
  - `routing`

**Comment by ctran** [comment] 2015-12-27 06:11
Is this something introduced by your PR?

**Comment by FME-Daniel** [comment] 2016-01-26 18:06
I don't have the time to put in a PR for this but the issue lies in `lib/annotate/annotate_models.rb:366`. The problem is caused by the key for the position being passed in to to the `annotate_one_file` method instead of relying on the already evaluated position that was merged in to the options.
```ruby
new_content = %w(after bottom).include?(options[position].to_s) ?
```
should instead be
```ruby
new_content = %w(after bottom).include?(options[:position].to_s) ?
```

**Comment by FME-Daniel** [comment] 2016-01-26 18:16
Granted, the new `position_in_*` keys are missing, as well. However, with the way the position is handled in the annotate_one_file method the fallback is ignored.

**Closed** 2019-02-14 16:39 UTC
Labels: reviewed
